In [1]:
import pandas as pd
import numpy as np
from pydataset import data
from math import sqrt

In [2]:
first_die = np.random.choice([1, 2, 3, 4, 5, 6], size=100_000)
second_die = np.random.choice([1, 2, 3, 4, 5, 6], size=100_000)

first_die, second_die

(array([3, 5, 3, ..., 4, 3, 5]), array([5, 1, 2, ..., 1, 6, 3]))

In [5]:
doubles = (first_die == second_die)
doubles.mean()

0.16736

In [6]:
outcomes = [1, 0]
flips = np.random.choice(outcomes, size=(100_000, 8))
flips

array([[0, 0, 1, ..., 0, 0, 0],
       [0, 1, 1, ..., 0, 0, 1],
       [0, 1, 1, ..., 1, 0, 1],
       ...,
       [1, 1, 0, ..., 0, 1, 0],
       [1, 1, 0, ..., 1, 1, 0],
       [1, 1, 1, ..., 1, 0, 0]])

In [8]:
three_heads = (flips.sum(axis=1) == 3)
three_heads.mean()

0.21772

In [9]:
outcomes = [1, 0]
flips = np.random.choice(outcomes, size=(100_000, 8))

more_than_three_heads = (flips.sum(axis=1) > 3)
more_than_three_heads.mean()

0.63597

In [15]:
# wedev = 1, ds = 0
outcomes = [1, 1, 1, 0]

alumni = np.random.choice(outcomes, size=(100_000, 2))
alumni

array([[1, 1],
       [0, 1],
       [0, 0],
       ...,
       [1, 1],
       [1, 1],
       [0, 0]])

In [20]:
ds_billboards = alumni.sum(axis=1)

In [21]:
(ds_billboards == 0).mean()

0.06179

In [23]:
np.random.normal(loc = 3.0, scale = 1.5, size = 5)

array([ 3.74291055, -1.24939975,  3.10487966,  2.89236307,  3.44886931])